### ISSUE TITLE
Sorting of Eigenvalues

### ISSUE THREAD

**Issue by skn123** [yixuan/arpack-eigen#3]
Suppose if I were to compute eigenvalues by setting SELECT_EIGENVALUE::SMALLEST_ALGE, I still get eigenvalues arranged in largest magnitude. I had to change the following:

//SortEigenvalue<Scalar, LARGEST_MAGN> sorting(ritz_val.data(), nev);
  SortEigenvalue<Scalar, SelectionRule> sorting(ritz_val.data(), nev);
in SymEigsSolver.h

**Comment by yixuan** [comment]
Hi @skn123 ,

SELECT_EIGENVALUE is the **selection** rule of eigenvalues. The returned eigenvalues are **always** sorted in decreasing order, which is the convention of most eigenvalue solvers.

Also, suggested by ggael, I renamed this library to [Spectra](https://github.com/yixuan/spectra) with a separate repository. All future development goes there and arpack-eigen is kept as an archive. I would suggest future issues being reported there. Thanks!
